// Generated by scripts/update-changelog.ps1 -- do not edit manually
// Source: git annotated tags
// var (not const) so window.CHANGELOG is accessible across scripts

var CHANGELOG = [
  { version: 'v1.3.0', date: '2026-05-10', message: 'Merge pull request #17 from Fideliuss/develop' },
  { version: 'v1.2.4', date: '2026-05-10', message: 'corrections texte + alignement signature' },
  { version: 'v1.2.3', date: '2026-05-09', message: 'destinataire à droite, footer remonté' },
  { version: 'v1.2.2', date: '2026-05-09', message: 'ajustements mise en page courriers' },
  { version: 'v1.2.1', date: '2026-05-09', message: 'footer courriers allégé' },
  { version: 'v1.2.0', date: '2026-05-09', message: 'Courriers PN + mise en page' },
];