# update-changelog.ps1
# Genere shared/changelog.js a partir des tags git.
# A relancer apres chaque nouveau tag : .\scripts\update-changelog.ps1

$root = Split-Path $PSScriptRoot -Parent
Set-Location $root

# Recupere tous les tags tries par version decroissante
$raw = git for-each-ref --sort=-version:refname `
  --format="%(refname:short)|%(objecttype)|%(taggerdate:format:%Y-%m-%d)|%(subject)" `
  refs/tags

$entries = foreach ($line in $raw) {
    $parts   = $line -split '\|', 4
    $ver     = $parts[0]
    $type    = $parts[1]
    $date    = $parts[2]
    $subject = $parts[3]

    # Tag leger : recuperer la date du commit pointe
    if ($type -ne 'tag' -or -not $date) {
        $date = git log -1 --format="%as" $ver
    }

    # Nettoyer le sujet : retirer le prefixe "vX.X.X <separateur> "
    # Gere tiret court, tiret long, em dash (U+2014) etc.
    $msg = $subject -replace '^v[\d.]+ .{1,3} ', ''
    # Si le sujet ne contient pas de separateur, garder tel quel
    if ($msg -eq $subject) { $msg = $subject }
    $msg = ($msg -split "`n")[0].Trim()

    [PSCustomObject]@{ version = $ver; date = $date; message = $msg }
}

# Serialiser en JS (UTF-8 sans BOM)
$jsLines = @(
    '// Generated by scripts/update-changelog.ps1 -- do not edit manually',
    '// Source: git annotated tags',
    '// var (not const) so window.CHANGELOG is accessible across scripts',
    '',
    'var CHANGELOG = ['
)

foreach ($e in $entries) {
    $v = $e.version -replace "'", "\'"
    $d = $e.date
    $m = $e.message -replace "'", "\'"
    $jsLines += "  { version: '$v', date: '$d', message: '$m' },"
}

$jsLines += '];'

$out     = $jsLines -join "`n"
$outPath = Join-Path $root 'shared\changelog.js'
$enc     = New-Object System.Text.UTF8Encoding $false  # UTF-8 sans BOM
[System.IO.File]::WriteAllText($outPath, $out, $enc)

Write-Host "changelog.js updated ($($entries.Count) tags)" -ForegroundColor Green
$entries | Format-Table -AutoSize
